<a href="https://colab.research.google.com/github/hakangungorr/dsa/blob/main/Chapter1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""

    This function takes two integers, n and m, and returns True if n is a multiple of m,
    that is, n = mi for some integer i, and False otherwise.
    """
def is_multiple(n,m):
  if n%m==0:
    return True
  else:
    return False




In [ ]:
""" Write a short Python function, is even(k), that takes an integer value and
 returns True if k is even, and False otherwise. However, your function
 cannot use the multiplication, modulo, or division """

x = int(input())



def is_even(k) :
  while k >= 2 :
    k -=2
  while k <= -2:
    k +=2
  return k ==0

print(is_even(x))

KeyboardInterrupt: Interrupted by user

In [ ]:
""" Write a short Python function, minmax(data), that takes a sequence of
 one or more numbers, and returns the smallest and largest numbers, in the
 form of a tuple of length two. Do not use the built-in functions min or
 max in implementing your solution."""

data =[-5,2,11,6,1,3,5,7,4,9,12]

def minmax(data:list):
  b , s = data[0] , data[0]
  for i in range(len(data)-1):
    if b < data[i+1]:
      b = data[i+1]
    if s > data[i+1]:
      s = data[i+1]

  return (s,b)

print(minmax(data))





(-5, 12)


In [ ]:
data =[-5,2,11,6,1,3,5,7,4,9,12]
def minmax(data):
  max, min = data[0] , data[0]
  for value in data:
    if value > max:
      max = value
    if value < min:
      min = value
  return(min,max)

minmax(data)

(-5, 12)

In [ ]:
"""R-1.4 Write a short Python function that takes a positive integer n and returns
the sum of the squares of all the positive integers smaller than n """
n = int(input())

def ds(n:int) -> int :
  sum = 0
  for i in range(1,n):
    sum += i**2
  return sum
ds(n)

4


14

In [ ]:
""" Write a short Python function that takes a positive integer n and returns
 the sum of the squares of all the odd positive integers smaller than n."""

def sumofsquares(n:int)->int:
  result = sum(i ** 2 for i in range(1, n) if i % 2 != 0)
  return result
n = int(input())
sumofsquares(n)


4


10

In [ ]:
""" What parameters should be sent to the range constructor, to produce a
 range with values 50, 60, 70, 80? """

for i in range(50,90,10):
  print(i, end= " ")




50 60 70 80 

In [ ]:
"""What parameters should be sent to the range constructor, to produce a
 range with values 8, 6, 4, 2, 0, −2, −4, −6, −8? """

for n in range(8,-9,-2):
  print(n, end=" ")


8 6 4 2 0 -2 -4 -6 -8 

In [ ]:
""" Demonstrate how to use Python’s list comprehension syntax to produce
 the list [1, 2, 4, 8, 16, 32, 64, 128, 256]."""

def exp(n:int)->list :
  list = []
  for i in range(n):
    list.append(2**i)
  return list

n = int(input())
exp(n)





9


[1, 2, 4, 8, 16, 32, 64, 128, 256]

In [ ]:
""" Demonstrate how to use Python’s list comprehension syntax to produce
 the list [1, 2, 4, 8, 16, 32, 64, 128, 256]."""
def exp(n:int)->list :
  result = [2**i for i in range(n+1)]
  return result


n = int(input())
exp(n)


3


[1, 2, 4, 8]

In [ ]:
"""Python’s random module includes a function choice(data) that returns a
 random element from a non-empty sequence. The random module in
cludes a more basic function randrange, with parameterization similar to
 the built-in range function, that return a random choice from the given
 range. Using only the randrange function, implement your own version
 of the choice function"""



import random

def my_choice(data):
    index = random.randrange(len(data))  # Verilen veri kümesinin uzunluğuna göre rastgele bir indeks seç
    return data[index]  # Seçilen indeksteki elemanı döndür

# Örnek kullanım
data = [10, 20, 30, 40, 50]
print(my_choice(data))

20


In [5]:

""" Create an array y=⎛⎝⎜323528359⎞⎠⎟
 and calculate the transpose of the array."""
import numpy as np
np.array([[3,5,3],[2,2,5],[3,8,9]])

array([[3, 5, 3],
       [2, 2, 5],
       [3, 8, 9]])

In [10]:
"""Create a zero array with size (2, 4)."""

x = np.zeros((2,4))
x[0,1] = 2
x[1,1] = 2
x

array([[0., 2., 0., 0.],
       [0., 2., 0., 0.]])

In [15]:
""" Generate an array with size 100 evenly spaced between -10 to 10 using linspace function in Numpy."""

np.linspace(-10,10,100)

array([-10.        ,  -9.7979798 ,  -9.5959596 ,  -9.39393939,
        -9.19191919,  -8.98989899,  -8.78787879,  -8.58585859,
        -8.38383838,  -8.18181818,  -7.97979798,  -7.77777778,
        -7.57575758,  -7.37373737,  -7.17171717,  -6.96969697,
        -6.76767677,  -6.56565657,  -6.36363636,  -6.16161616,
        -5.95959596,  -5.75757576,  -5.55555556,  -5.35353535,
        -5.15151515,  -4.94949495,  -4.74747475,  -4.54545455,
        -4.34343434,  -4.14141414,  -3.93939394,  -3.73737374,
        -3.53535354,  -3.33333333,  -3.13131313,  -2.92929293,
        -2.72727273,  -2.52525253,  -2.32323232,  -2.12121212,
        -1.91919192,  -1.71717172,  -1.51515152,  -1.31313131,
        -1.11111111,  -0.90909091,  -0.70707071,  -0.50505051,
        -0.3030303 ,  -0.1010101 ,   0.1010101 ,   0.3030303 ,
         0.50505051,   0.70707071,   0.90909091,   1.11111111,
         1.31313131,   1.51515152,   1.71717172,   1.91919192,
         2.12121212,   2.32323232,   2.52525253,   2.72

12
